### ISSUE TITLE
Telekom Challenge Work

### ISSUE THREAD

**Issue by GR3G0RYO** [rddl-network/0x21e8#72]
To be filled in by Jurgen for work this Sprint:
1. Uploading Tasmota firmware to Sonoff that can sign payloads. To be done by Tom, Stefan and Maurice.
2.  Reading from Sonoff the consumed watt amount of the laptop and turning this data into a Planetmint transaction. Then connecting the CID result of this transaction to a resolver so that we can showcase the watt amount when exploring the transaction online. To be done by Stefan and Jürgen.
3. To better demonstrate the trust anchor, we will also put a TA outside the Sonoff casing. This TA will be attested the same way the Sonoff device internally is attested - both will share the same mnemonic phrase. To be done by Tom and Juergen-
4. verify the endpoint to verify if the CID content got signed with a given public key/TA verify.rddl.io

**Comment by eckelj** [comment]
step 2) has been done! via the rddl-client: https://www.notion.so/riddlecode/Sequence-Interaction-Diagrams-e7bb41e7f9084c62a7aa04c5049b0c48?pvs=4#70a8cbed39204f29832b36559d4d3052
